const keyboardKeys = [
  [
    ['', 'Backquote', '§', '±', '`', '~'],
    ['', 'Digit1', 'ą', 'Ą', '1', '!'],
    ['', 'Digit2', 'č', 'Č', '2', '@'],
    ['', 'Digit3', 'ę', 'Ę', '3', '#'],
    ['', 'Digit4', 'ė', 'Ė', '4', '$'],
    ['', 'Digit5', 'į', 'Į', '5', '%'],
    ['', 'Digit6', 'š', 'Š', '6', '^'],
    ['', 'Digit7', 'ų', 'Ų', '7', '&'],
    ['', 'Digit8', 'ū', 'Ū', '8', '*'],
    ['', 'Digit9', '9', '(', '9', '('],
    ['', 'Digit0', '0', ')', '0', ')'],
    ['', 'Minus', '-', '_', '-', '_'],
    ['', 'Equal', '=', '+', '=', '+'],
    ['backspace', 'Backspace', 'Backspace', 'Backspace', 'Backspace', 'Backspace'],
  ],
  [
    ['tab', 'Tab', 'Tab', 'Tab', 'Tab', 'Tab'],
    ['', 'KeyQ', 'q', 'Q', 'q', 'Q'],
    ['', 'KeyW', 'w', 'W', 'w', 'W'],
    ['', 'KeyE', 'e', 'E', 'e', 'E'],
    ['', 'KeyR', 'r', 'R', 'r', 'R'],
    ['', 'KeyT', 't', 'T', 't', 'T'],
    ['', 'KeyY', 'y', 'Y', 'y', 'Y'],
    ['', 'KeyU', 'u', 'U', 'u', 'U'],
    ['', 'KeyI', 'i', 'I', 'i', 'I'],
    ['', 'KeyO', 'o', 'O', 'o', 'O'],
    ['', 'KeyP', 'p', 'P', 'p', 'P'],
    ['', 'BracketLeft', '[', '{', '[', '{'],
    ['', 'BracketRight', ']', '}', ']', '}'],
    ['', 'Backslash', '\\', '/', '\\', '|'],
    ['del', 'Delete', 'Del', 'Del', 'Del', 'Del', 'Del'],
  ],
  [
    ['capslock', 'CapsLock', 'CapsLock', 'CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
    ['', 'KeyA', 'a', 'A', 'a', 'A'],
    ['', 'KeyS', 's', 'S', 's', 'S'],
    ['', 'KeyD', 'd', 'D', 'd', 'D'],
    ['', 'KeyF', 'f', 'F', 'f', 'F'],
    ['', 'KeyG', 'g', 'G', 'g', 'G'],
    ['', 'KeyH', 'h', 'H', 'h', 'H'],
    ['', 'KeyJ', 'j', 'J', 'j', 'J'],
    ['', 'KeyK', 'k', 'K', 'k', 'K'],
    ['', 'KeyL', 'l', 'L', 'l', 'L'],
    ['', 'Semicolon', ';', ':', ';', ':'],
    ['', 'Quote', "'", '"', "'", '"'],
    ['enter', 'Enter', 'Enter', 'Enter', 'Enter', 'Enter'],
  ],
  [
    ['shift-left', 'ShiftLeft', 'Shift', 'Shift', 'Shift', 'Shift'],
    ['', 'KeyZ', 'z', 'Z', 'z', 'Z'],
    ['', 'KeyX', 'x', 'X', 'x', 'X'],
    ['', 'KeyC', 'c', 'C', 'c', 'C'],
    ['', 'KeyV', 'v', 'V', 'v', 'V'],
    ['', 'KeyB', 'b', 'B', 'b', 'B'],
    ['', 'KeyN', 'n', 'N', 'n', 'N'],
    ['', 'KeyM', 'm', 'M', 'm', 'M'],
    ['', 'Comma', ',', '<', '.', '<'],
    ['', 'Period', '.', '>', ',', '>'],
    ['', 'Slash', '/', '?', '/', '?'],
    ['arrow', 'ArrowUp', '↑', '↑', '↑', '↑'],
    ['shift-right', 'ShiftRight', 'Shift', 'Shift', 'Shift', 'Shift'],
  ],
  [
    ['ctrl-left', 'ControlLeft', 'Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
    ['win', 'MetaLeft', 'Win', 'Win', 'Win', 'Win'],
    ['alt-left', 'AltLeft', 'Alt', 'Alt', 'Alt', 'Alt'],
    ['space', 'Space', ' ', ' ', ' ', ' '],
    ['alt-right', 'AltRight', 'Alt', 'Alt', 'Alt', 'Alt'],
    ['arrow', 'ArrowLeft', '←', '←', '←', '←'],
    ['arrow', 'ArrowDown', '↓', '↓', '↓', '↓'],
    ['arrow', 'ArrowRight', '→', '→', '→', '→'],
    ['ctrl-right', 'ControlRight', 'Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  ],
];

export default keyboardKeys;
